language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl1.2-dev libasound2-dev libpng-dev libz-dev
script: ./configure --platform=libretro && make
